### ISSUE TITLE
League of Legends

### ISSUE THREAD

**Issue by clovisd** [Cog-Creators/Cog-Board#6]
Fetch info about players, get build paths, etc.

*Edit:
Assigned to @QingyuChai
-- Kowlin*

**Comment by Chovin** [comment]
http://cogs.red/cogs/QingyuChai/RiceCogs/league/

^ is this not sufficient? 
I believe there was also a cog that got the map n added data to it as well.

**Comment by clovisd** [comment]
The League Cog is utterly useless. All it does is generate links to a website by adding your username at the end of an expression: na.op.gg/summoner/userName=(insert username here)

**Comment by Adeft** [comment]
Jumping on this. A cog that gives current info about the team/enemy %winrate rank etc. Top bans,  counters.

**Comment by Chovin** [comment]
you'll be making the cog @Adeft ?

**Comment by Adeft** [comment]
No, jumping on. Like in supporting the idea.  I dont think its to hard to make but i got no experience.

**Comment by QingyuChai** [comment]
I do agree that my league cog is kind of useless right now. I might add features requested features in the future if enough people want it.

**Comment by QingyuChai** [comment]
I can confirm that I am now working on a League Cog that is supported by the Riot Api. Fetching player info will definitely be possible, as well as match history. Getting build paths will be harder, but I'll see what I can do. @Chovin, could you assign this to me?

**Comment by Kowlin** [comment]
Why u no edit original comment @palmtree5 >:(

**Comment by clovisd** [comment]
Woo! Thanks for doing this @QingyuChai ! :)

I know of a couple bots out there that might be useful for inspiration (features, commands, etc).
Here are the one's I've been using:

1. https://github.com/Gravebot/Gravebot (GraveBot) see League Of Legends section.
2. https://www.reddit.com/r/leagueoflegends/comments/4pd5zr/discrank_a_discord_chat_bot/ (Discrank)  has some interesting stat displays (text based tables, etc).

**Comment by QingyuChai** [comment]
@clovisd Could you add FwiedWice#2789 on Discord? Would be easier for me to know what you are looking for.

**Comment by QingyuChai** [comment]
Hello! I have a version available that works as intended, just not as fast as intended. Because of a rate limit on API requests you can make to Riot Games, it might take a while to generate match info, and in that time the bot does not respond to other commands. 
Also, you are required to get an API key from both [Riot Games](https://developer.riotgames.com/terms-and-conditions.html) and [Champion.gg](http://api.champion.gg/)




You can choose what key you use on your bot with [p]leagueset

You can find the cog [here](https://github.com/QingyuChai/RiceCogs/tree/master/league)

Again, only getting the current match info will lag out the bot. Other commands are fine.

For further suggestions/ideas/thoughts/anything please visit [this link](https://github.com/QingyuChai/RiceCogs/issues).

**Comment by clovisd** [comment]
Great! Thanks :)
