### ISSUE TITLE
[Paid] User-assignable roles - but only one from a list at any time

### ISSUE THREAD

**Issue by QuietRepentance** [Cog-Creators/Cog-Board#84]
## Description of cog:

I'm looking for a cog that will allow users to self assign a role, but will only allow them one role at a time from a list, replacing any old role from that list if they have it.

## API's or other information for cog:

Requirements:
-Role swapping must be a 1 step process for the user. We want to avoid a multiple command process (like one to leave role, one to join), so the command must check and remove any relevant pre-existing roles in addition to assigning the new one.
-Role selection in the command must be case-insensitive. (e.g "[p]cmd Character" will work, as will "[p]cmd character".)
-Must be able to support two different commands with their own separate role lists/role categories.

## Other info (Bounty, issues, ETC):

Paid work, $25.

Feel free to contact me @ Quiet#8251 and I can try to provide all relevant info.

**Comment by calebj** [comment]
I'm actually working on combining the best features of punish, warning and selfrole into a single cog. This is one of the planned features. The finished product will probably take longer than this feature by itself. If you want to wait, I'll consider this as a priority support feature. Otherwise, someone else can take this up.

You should also specify v2 or v3.

**Comment by calebj** [comment]
This bounty has been completed; awaiting testing, verification of met requirements and payment.

**Comment by calebj** [comment]
This bounty is complete. @QuietRepentance please confirm so this can be closed.

**Comment by calebj** [comment]
Close this.
